




tpc_ds_schema = {
    # Fact Tables
    'store_sales': {
        'ss_sold_date_sk': 'numerical',
        'ss_sold_time_sk': 'numerical',
        'ss_item_sk': 'string',
        'ss_customer_sk': 'string',
        'ss_cdemo_sk': 'string',
        'ss_hdemo_sk': 'string',
        'ss_addr_sk': 'string',
        'ss_store_sk': 'string',
        'ss_promo_sk': 'string',
        'ss_ticket_number': 'string',
        'ss_quantity': 'numerical',
        'ss_wholesale_cost': 'numerical',
        'ss_list_price': 'numerical',
        'ss_sales_price': 'numerical',
        'ss_ext_discount_amt': 'numerical',
        'ss_ext_sales_price': 'numerical',
        'ss_ext_wholesale_cost': 'numerical',
        'ss_ext_list_price': 'numerical',
        'ss_ext_tax': 'numerical',
        'ss_coupon_amt': 'numerical',
        'ss_net_paid': 'numerical',
        'ss_net_paid_inc_tax': 'numerical',
        'ss_net_profit': 'numerical',
    },
    'store_returns': {
        'sr_returned_date_sk': 'numerical',
        'sr_return_time_sk': 'numerical',
        'sr_item_sk': 'string',
        'sr_customer_sk': 'string',
        'sr_cdemo_sk': 'string',
        'sr_hdemo_sk': 'string',
        'sr_addr_sk': 'string',
        'sr_store_sk': 'string',
        'sr_reason_sk': 'string',
        'sr_ticket_number': 'string',
        'sr_return_quantity': 'numerical',
        'sr_return_amt': 'numerical',
        'sr_return_tax': 'numerical',
        'sr_return_amt_inc_tax': 'numerical',
        'sr_fee': 'numerical',
        'sr_return_ship_cost': 'numerical',
        'sr_refunded_cash': 'numerical',
        'sr_reversed_charge': 'numerical',
        'sr_store_credit': 'numerical',
        'sr_net_loss': 'numerical',
    },
    'catalog_sales': {
        'cs_sold_date_sk': 'numerical',
        'cs_sold_time_sk': 'numerical',
        'cs_ship_date_sk': 'numerical',
        'cs_bill_customer_sk': 'string',
        'cs_bill_cdemo_sk': 'string',
        'cs_bill_hdemo_sk': 'string',
        'cs_bill_addr_sk': 'string',
        'cs_ship_customer_sk': 'string',
        'cs_ship_cdemo_sk': 'string',
        'cs_ship_hdemo_sk': 'string',
        'cs_ship_addr_sk': 'string',
        'cs_call_center_sk': 'string',
        'cs_catalog_page_sk': 'string',
        'cs_ship_mode_sk': 'string',
        'cs_warehouse_sk': 'string',
        'cs_item_sk': 'string',
        'cs_promo_sk': 'string',
        'cs_order_number': 'string',
        'cs_quantity': 'numerical',
        'cs_wholesale_cost': 'numerical',
        'cs_list_price': 'numerical',
        'cs_sales_price': 'numerical',
        'cs_ext_discount_amt': 'numerical',
        'cs_ext_sales_price': 'numerical',
        'cs_ext_wholesale_cost': 'numerical',
        'cs_ext_list_price': 'numerical',
        'cs_ext_tax': 'numerical',
        'cs_coupon_amt': 'numerical',
        'cs_ext_ship_cost': 'numerical',
        'cs_net_paid': 'numerical',
        'cs_net_paid_inc_tax': 'numerical',
        'cs_net_paid_inc_ship': 'numerical',
        'cs_net_paid_inc_ship_tax': 'numerical',
        'cs_net_profit': 'numerical',
    },
    'catalog_returns': {
        'cr_returned_date_sk': 'numerical',
        'cr_returned_time_sk': 'numerical',
        'cr_item_sk': 'string',
        'cr_refunded_customer_sk': 'string',
        'cr_refunded_cdemo_sk': 'string',
        'cr_refunded_hdemo_sk': 'string',
        'cr_refunded_addr_sk': 'string',
        'cr_returning_customer_sk': 'string',
        'cr_returning_cdemo_sk': 'string',
        'cr_returning_hdemo_sk': 'string',
        'cr_returning_addr_sk': 'string',
        'cr_call_center_sk': 'string',
        'cr_catalog_page_sk': 'string',
        'cr_ship_mode_sk': 'string',
        'cr_warehouse_sk': 'string',
        'cr_reason_sk': 'string',
        'cr_order_number': 'string',
        'cr_return_quantity': 'numerical',
        'cr_return_amt': 'numerical',
        'cr_return_tax': 'numerical',
        'cr_return_amt_inc_tax': 'numerical',
        'cr_fee': 'numerical',
        'cr_return_ship_cost': 'numerical',
        'cr_refunded_cash': 'numerical',
        'cr_reversed_charge': 'numerical',
        'cr_store_credit': 'numerical',
        'cr_net_loss': 'numerical',
    },
    'web_sales': {
        'ws_sold_date_sk': 'numerical',
        'ws_sold_time_sk': 'numerical',
        'ws_ship_date_sk': 'numerical',
        'ws_item_sk': 'string',
        'ws_bill_customer_sk': 'string',
        'ws_bill_cdemo_sk': 'string',
        'ws_bill_hdemo_sk': 'string',
        'ws_bill_addr_sk': 'string',
        'ws_ship_customer_sk': 'string',
        'ws_ship_cdemo_sk': 'string',
        'ws_ship_hdemo_sk': 'string',
        'ws_ship_addr_sk': 'string',
        'ws_web_page_sk': 'string',
        'ws_web_site_sk': 'string',
        'ws_ship_mode_sk': 'string',
        'ws_warehouse_sk': 'string',
        'ws_promo_sk': 'string',
        'ws_order_number': 'string',
        'ws_quantity': 'numerical',
        'ws_wholesale_cost': 'numerical',
        'ws_list_price': 'numerical',
        'ws_sales_price': 'numerical',
        'ws_ext_discount_amt': 'numerical',
        'ws_ext_sales_price': 'numerical',
        'ws_ext_wholesale_cost': 'numerical',
        'ws_ext_list_price': 'numerical',
        'ws_ext_tax': 'numerical',
        'ws_coupon_amt': 'numerical',
        'ws_ext_ship_cost': 'numerical',
        'ws_net_paid': 'numerical',
        'ws_net_paid_inc_tax': 'numerical',
        'ws_net_paid_inc_ship': 'numerical',
        'ws_net_paid_inc_ship_tax': 'numerical',
        'ws_net_profit': 'numerical',
    },
    'web_returns': {
        'wr_returned_date_sk': 'numerical',
        'wr_returned_time_sk': 'numerical',
        'wr_item_sk': 'string',
        'wr_refunded_customer_sk': 'string',
        'wr_refunded_cdemo_sk': 'string',
        'wr_refunded_hdemo_sk': 'string',
        'wr_refunded_addr_sk': 'string',
        'wr_returning_customer_sk': 'string',
        'wr_returning_cdemo_sk': 'string',
        'wr_returning_hdemo_sk': 'string',
        'wr_returning_addr_sk': 'string',
        'wr_web_page_sk': 'string',
        'wr_reason_sk': 'string',
        'wr_order_number': 'string',
        'wr_return_quantity': 'numerical',
        'wr_return_amt': 'numerical',
        'wr_return_tax': 'numerical',
        'wr_return_amt_inc_tax': 'numerical',
        'wr_fee': 'numerical',
        'wr_return_ship_cost': 'numerical',
        'wr_refunded_cash': 'numerical',
        'wr_reversed_charge': 'numerical',
        'wr_account_credit': 'numerical',
        'wr_net_loss': 'numerical',
    },
    'inventory': {
        'inv_date_sk': 'numerical',
        'inv_item_sk': 'string',
        'inv_warehouse_sk': 'string',
        'inv_quantity_on_hand': 'numerical',
    },

    # Dimension Tables
    'store': {
        's_store_sk': 'string',
        's_store_id': 'string',
        's_rec_start_date': 'string',
        's_rec_end_date': 'string',
        's_closed_date_sk': 'numerical',
        's_store_name': 'string',
        's_number_employees': 'numerical',
        's_floor_space': 'numerical',
        's_hours': 'string',
        's_manager': 'string',
        's_market_id': 'string',
        's_geography_class': 'string',
        's_market_desc': 'string',
        's_market_manager': 'string',
        's_division_id': 'string',
        's_division_name': 'string',
        's_company_id': 'string',
        's_company_name': 'string',
        's_street_number': 'string',
        's_street_name': 'string',
        's_street_type': 'string',
        's_suite_number': 'string',
        's_city': 'string',
        's_county': 'string',
        's_state': 'string',
        's_zip': 'string',
        's_country': 'string',
        's_gmt_offset': 'numerical',
        's_tax_percentage': 'numerical',
    },
    'call_center': {
        'cc_call_center_sk': 'string',
        'cc_call_center_id': 'string',
        'cc_rec_start_date': 'string',
        'cc_rec_end_date': 'string',
        'cc_closed_date_sk': 'numerical',
        'cc_open_date_sk': 'numerical',
        'cc_name': 'string',
        'cc_class': 'string',
        'cc_employees': 'numerical',
        'cc_sq_ft': 'numerical',
        'cc_hours': 'string',
        'cc_manager': 'string',
        'cc_mkt_id': 'string',
        'cc_mkt_class': 'string',
        'cc_mkt_desc': 'string',
        'cc_market_manager': 'string',
        'cc_division': 'numerical',
        'cc_division_name': 'string',
        'cc_company': 'numerical',
        'cc_company_name': 'string',
        'cc_street_number': 'string',
        'cc_street_name': 'string',
        'cc_street_type': 'string',
        'cc_suite_number': 'string',
        'cc_city': 'string',
        'cc_county': 'string',
        'cc_state': 'string',
        'cc_zip': 'string',
        'cc_country': 'string',
        'cc_gmt_offset': 'numerical',
        'cc_tax_percentage': 'numerical',
    },
    'catalog_page': {
        'cp_catalog_page_sk': 'string',
        'cp_catalog_page_id': 'string',
        'cp_start_date_sk': 'numerical',
        'cp_end_date_sk': 'numerical',
        'cp_department': 'string',
        'cp_catalog_number': 'numerical',
        'cp_catalog_page_number': 'numerical',
        'cp_description': 'string',
        'cp_type': 'string',
    },
    'web_site': {
        'web_site_sk': 'string',
        'web_site_id': 'string',
        'web_rec_start_date': 'string',
        'web_rec_end_date': 'string',
        'web_name': 'string',
        'web_open_date_sk': 'numerical',
        'web_close_date_sk': 'numerical',
        'web_class': 'string',
        'web_manager': 'string',
        'web_mkt_id': 'string',
        'web_mkt_class': 'string',
        'web_mkt_desc': 'string',
        'web_market_manager': 'string',
        'web_company_id': 'string',
        'web_company_name': 'string',
        'web_street_number': 'string',
        'web_street_name': 'string',
        'web_street_type': 'string',
        'web_suite_number': 'string',
        'web_city': 'string',
        'web_county': 'string',
        'web_state': 'string',
        'web_zip': 'string',
        'web_country': 'string',
        'web_gmt_offset': 'numerical',
        'web_tax_percentage': 'numerical',
    },
    'web_page': {
        'wp_web_page_sk': 'string',
        'wp_web_page_id': 'string',
        'wp_rec_start_date': 'string',
        'wp_rec_end_date': 'string',
        'wp_creation_date_sk': 'numerical',
        'wp_access_date_sk': 'numerical',
        'wp_autogen_flag': 'string',
        'wp_customer_sk': 'string',
        'wp_url': 'string',
        'wp_type': 'string',
        'wp_char_count': 'numerical',
        'wp_link_count': 'numerical',
        'wp_image_count': 'numerical',
        'wp_max_ad_count': 'numerical',
    },
    'warehouse': {
        'w_warehouse_sk': 'string',
        'w_warehouse_id': 'string',
        'w_warehouse_name': 'string',
        'w_warehouse_sq_ft': 'numerical',
        'w_street_number': 'string',
        'w_street_name': 'string',
        'w_street_type': 'string',
        'w_suite_number': 'string',
        'w_city': 'string',
        'w_county': 'string',
        'w_state': 'string',
        'w_zip': 'string',
        'w_country': 'string',
        'w_gmt_offset': 'numerical',
    },
    'customer': {
        'c_customer_sk': 'string',
        'c_customer_id': 'string',
        'c_current_cdemo_sk': 'string',
        'c_current_hdemo_sk': 'string',
        'c_current_addr_sk': 'string',
        'c_first_shipto_date_sk': 'numerical',
        'c_first_sales_date_sk': 'numerical',
        'c_salutation': 'string',
        'c_first_name': 'string',
        'c_last_name': 'string',
        'c_preferred_cust_flag': 'string',
        'c_birth_day': 'numerical',
        'c_birth_month': 'numerical',
        'c_birth_year': 'numerical',
        'c_birth_country': 'string',
        'c_login': 'string',
        'c_email_address': 'string',
        'c_last_review_date_sk': 'numerical',
    },
    'customer_address': {
        'ca_address_sk': 'string',
        'ca_address_id': 'string',
        'ca_street_number': 'string',
        'ca_street_name': 'string',
        'ca_street_type': 'string',
        'ca_suite_number': 'string',
        'ca_city': 'string',
        'ca_county': 'string',
        'ca_state': 'string',
        'ca_zip': 'string',
        'ca_country': 'string',
        'ca_gmt_offset': 'numerical',
        'ca_location_type': 'string',
    },
    'customer_demographics': {
        'cd_demo_sk': 'string',
        'cd_gender': 'string',
        'cd_marital_status': 'string',
        'cd_education_status': 'string',
        'cd_purchase_estimate': 'numerical',
        'cd_credit_rating': 'string',
        'cd_dep_count': 'numerical',
        'cd_dep_employed_count': 'numerical',
        'cd_dep_college_count': 'numerical',
    },
    'date_dim': {
        'd_date_sk': 'numerical',
        'd_date_id': 'string',
        'd_date': 'string',
        'd_month_seq': 'numerical',
        'd_week_seq': 'numerical',
        'd_quarter_seq': 'numerical',
        'd_year': 'numerical',
        'd_dow': 'numerical',
        'd_moy': 'numerical',
        'd_dom': 'numerical',
        'd_qoy': 'numerical',
        'd_fy_year': 'numerical',
        'd_fy_quarter_seq': 'numerical',
        'd_fy_week_seq': 'numerical',
        'd_day_name': 'string',
        'd_quarter_name': 'string',
        'd_holiday': 'string',
        'd_weekend': 'string',
        'd_following_holiday': 'string',
        'd_first_dom': 'numerical',
        'd_last_dom': 'numerical',
        'd_same_day_ly': 'numerical',
        'd_same_day_lq': 'numerical',
        'd_current_day': 'string',
        'd_current_week': 'string',
        'd_current_month': 'string',
        'd_current_quarter': 'string',
        'd_current_year': 'string',
    },
    'household_demographics': {
        'hd_demo_sk': 'string',
        'hd_income_band_sk': 'string',
        'hd_buy_potential': 'string',
        'hd_dep_count': 'numerical',
        'hd_vehicle_count': 'numerical',
    },
    'item': {
        'i_item_sk': 'string',
        'i_item_id': 'string',
        'i_rec_start_date': 'string',
        'i_rec_end_date': 'string',
        'i_item_desc': 'string',
        'i_current_price': 'numerical',
        'i_wholesale_cost': 'numerical',
        'i_brand_id': 'string',
        'i_brand': 'string',
        'i_class_id': 'string',
        'i_class': 'string',
        'i_category_id': 'string',
        'i_category': 'string',
        'i_manufact_id': 'string',
        'i_manufact': 'string',
        'i_size': 'string',
        'i_formulation': 'string',
        'i_color': 'string',
        'i_units': 'string',
        'i_container': 'string',
        'i_manager_id': 'string',
        'i_product_name': 'string',
    },
    'income_band': {
        'ib_income_band_sk': 'string',
        'ib_lower_bound': 'numerical',
        'ib_upper_bound': 'numerical',
    },
    'promotion': {
        'p_promo_sk': 'string',
        'p_promo_id': 'string',
        'p_start_date_sk': 'numerical',
        'p_end_date_sk': 'numerical',
        'p_item_sk': 'string',
        'p_cost': 'numerical',
        'p_response_target': 'numerical',
        'p_promo_name': 'string',
        'p_channel_dmail': 'string',
        'p_channel_email': 'string',
        'p_channel_catalog': 'string',
        'p_channel_tv': 'string',
        'p_channel_radio': 'string',
        'p_channel_press': 'string',
        'p_channel_event': 'string',
        'p_channel_demo': 'string',
        'p_channel_details': 'string',
        'p_purpose': 'string',
        'p_discount_active': 'string',
    },
    'reason': {
        'r_reason_sk': 'string',
        'r_reason_id': 'string',
        'r_reason_desc': 'string',
    },
    'ship_mode': {
        'sm_ship_mode_sk': 'string',
        'sm_ship_mode_id': 'string',
        'sm_type': 'string',
        'sm_code': 'string',
        'sm_carrier': 'string',
        'sm_contract': 'string',
    },
    'time_dim': {
        't_time_sk': 'numerical',
        't_time_id': 'string',
        't_time': 'numerical',
        't_hour': 'numerical',
        't_minute': 'numerical',
        't_second': 'numerical',
        't_am_pm': 'string',
        't_shift': 'string',
        't_sub_shift': 'string',
        't_meal_time': 'string',
    },
}







TPCDS_DDL = {
    "catalog_sales": ("""
    CREATE TABLE catalog_sales (
	    cs_sold_date_sk          INTEGER,
	    cs_sold_time_sk          INTEGER,
	    cs_ship_date_sk          INTEGER,
	    cs_bill_customer_sk      INTEGER,
	    cs_bill_cdemo_sk         INTEGER,
	    cs_bill_hdemo_sk         INTEGER,
	    cs_bill_addr_sk          INTEGER,
	    cs_ship_customer_sk      INTEGER,
	    cs_ship_cdemo_sk         INTEGER,
	    cs_ship_hdemo_sk         INTEGER,
	    cs_ship_addr_sk          INTEGER,
	    cs_call_center_sk        INTEGER,
	    cs_catalog_page_sk       INTEGER,
	    cs_ship_mode_sk          INTEGER,
	    cs_warehouse_sk          INTEGER,
	    cs_item_sk               INTEGER,
	    cs_promo_sk              INTEGER,
	    cs_order_number          BIGINT,
	    cs_quantity              INTEGER,
	    cs_wholesale_cost        DECIMAL(7,2),
	    cs_list_price            DECIMAL(7,2),
	    cs_sales_price           DECIMAL(7,2),
	    cs_ext_discount_amt      DECIMAL(7,2),
	    cs_ext_sales_price       DECIMAL(7,2),
	    cs_ext_wholesale_cost    DECIMAL(7,2),
	    cs_ext_list_price        DECIMAL(7,2),
	    cs_ext_tax               DECIMAL(7,2),
	    cs_coupon_amt            DECIMAL(7,2),
	    cs_ext_ship_cost         DECIMAL(7,2),
	    cs_net_paid              DECIMAL(7,2),
	    cs_net_paid_inc_tax      DECIMAL(7,2),
	    cs_net_paid_inc_ship     DECIMAL(7,2),
	    cs_net_paid_inc_ship_tax DECIMAL(7,2),
	    cs_net_profit            DECIMAL(7,2)
    );
    """, '../sample_tpcds_table/table/catalog_sales.dat')    
}




filter_operator_possible_columns = {
    "catalog_sales": {
    	'string_col'    :['cs_item_sk','cs_promo_sk','cs_bill_customer_sk'],
    	'numerical_col' :['cs_ext_sales_price','cs_quantity']
    }
}








